# Generated by Django 5.2.6 on 2025-09-18 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unspecified')], default='U', max_length=2)),
                ('breed', models.CharField(choices=[('D', 'Street Dog')], default='D', max_length=2)),
                ('age', models.IntegerField()),
                ('intake_reason', models.CharField(choices=[('R', 'Rescue'), ('T', 'Training')], max_length=2)),
                ('arrival_date', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('microchip_id', models.CharField(blank=True, max_length=10, null=True)),
                ('weight_kg', models.FloatField()),
                ('height_cm', models.FloatField()),
                ('color', models.CharField(choices=[('B', 'Black'), ('W', 'White'), ('G', 'Gray')], max_length=2)),
                ('detailed_description', models.TextField(blank=True)),
                ('health_status', models.CharField(choices=[('H', 'Healthy'), ('S', 'Sick')], default='H', max_length=2)),
                ('vaccination_status', models.CharField(choices=[('N', 'Not Vaccinated'), ('I', 'Incomplete'), ('C', 'Complete')], default='N', max_length=2)),
                ('castrated', models.BooleanField(default=False)),
                ('health_record', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='record_keeping.owner')),
            ],
        ),
    ]
