# Generated by Django 5.2.6 on 2025-09-18 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_keeping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='arrival_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
