# Generated by Django 5.2.6 on 2025-09-18 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_keeping', '0002_alter_dog_arrival_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='record_keeping.owner'),
        ),
    ]
