# Generated by Django 5.2.6 on 2025-09-20 12:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('charter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='records.charter')),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('name', models.CharField(max_length=64)),
                ('age_months', models.IntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unspecified')], default='U', max_length=32)),
                ('breed', models.CharField(choices=[('D', 'Street Dog'), ('MIXED', 'Mixed Breed'), ('GOLDEN', 'Golden Retriever'), ('GERMAN', 'German Shepherd'), ('OTHER', 'Other')], default='D', max_length=32)),
                ('microchip_status', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unspecified')], default='U', max_length=32)),
                ('microchip_id', models.CharField(blank=True, max_length=32, null=True)),
                ('intake_reason', models.CharField(choices=[('R', 'Rescue'), ('T', 'Training')], default='R', max_length=32)),
                ('arrival_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_adopted', models.BooleanField(default=False)),
                ('is_available_for_adoption', models.BooleanField(default=False)),
                ('adoption_date', models.DateTimeField(blank=True, null=True)),
                ('weight_kg', models.FloatField()),
                ('height_cm', models.FloatField()),
                ('color', models.CharField(choices=[('B', 'Black'), ('W', 'White'), ('G', 'Gray')], max_length=32)),
                ('detailed_description', models.TextField(blank=True)),
                ('health_status', models.CharField(choices=[('H', 'Healthy'), ('S', 'Sick'), ('P', 'Passed Away')], default='H', max_length=32)),
                ('vaccination_status', models.CharField(choices=[('N', 'Not Vaccinated'), ('I', 'Incomplete'), ('C', 'Complete'), ('U', 'Unspecified')], default='U', max_length=32)),
                ('castration_status', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unspecified')], default='U', max_length=32)),
                ('health_record', models.TextField(blank=True, default='Any sickness, injuries, pregnancies, castration or other procedures should be entered here.')),
                ('vaccination_record', models.TextField(blank=True, default='The name of the vaccines alongside of the date they were administered should be entered here')),
                ('treatment_record', models.TextField(blank=True, default='Any medication or treatment, with names, dosages and frequency should be entered here')),
                ('special_needs', models.TextField(blank=True)),
                ('behavioral_notes', models.TextField(blank=True)),
                ('other_notes', models.TextField(blank=True)),
                ('charter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dogs', to='records.charter')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adopted_dogs', to='records.contact')),
            ],
        ),
    ]
