# Generated by Django 5.2.6 on 2025-09-27 16:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntityInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('name', models.CharField(max_length=64)),
                ('age_months', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unspecified')], default='U', max_length=32)),
                ('breed', models.CharField(choices=[('D', 'Street Dog'), ('MIXED', 'Mixed Breed'), ('GOLDEN', 'Golden Retriever'), ('GERMAN', 'German Shepherd'), ('LAB', 'Labrador Retriever'), ('BEAGLE', 'Beagle'), ('BULL', 'Bulldog'), ('PIT', 'Pit Bull'), ('HUSKY', 'Siberian Husky'), ('CHI', 'Chihuahua'), ('POM', 'Pomeranian'), ('OTHER', 'Other')], default='D', max_length=32)),
                ('microchip_status', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unspecified')], default='U', max_length=32)),
                ('microchip_id', models.CharField(blank=True, max_length=32, null=True)),
                ('intake_status', models.CharField(choices=[('R', 'Rescue'), ('T', 'Training'), ('H', 'Hotel')], default='R', max_length=32)),
                ('arrival_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('passing_date', models.DateTimeField(blank=True, null=True)),
                ('passing_reason', models.TextField(blank=True, null=True)),
                ('burial_place', models.TextField(blank=True, null=True)),
                ('current_weight_kg', models.FloatField(blank=True, null=True)),
                ('height_cm', models.FloatField()),
                ('color', models.CharField(choices=[('B', 'Black'), ('W', 'White'), ('G', 'Gray'), ('BR', 'Brown'), ('T', 'Tan'), ('C', 'Cream'), ('GOLD', 'Golden'), ('R', 'Red'), ('BL', 'Blue'), ('MC', 'Multi-Color'), ('SP', 'Spotted'), ('ST', 'Striped')], max_length=32)),
                ('detailed_description', models.TextField(blank=True)),
                ('default_photo', models.ImageField(blank=True, help_text='Default photo for this dog', null=True, upload_to='photos/')),
                ('health_status', models.CharField(choices=[('H', 'Healthy'), ('S', 'Sick'), ('P', 'Passed Away'), ('U', 'Unspecified')], default='U', max_length=32)),
                ('vaccination_status', models.CharField(choices=[('N', 'Not Vaccinated'), ('I', 'Incomplete'), ('C', 'Complete'), ('U', 'Unspecified')], default='U', max_length=32)),
                ('castration_status', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unspecified')], default='U', max_length=32)),
                ('health_record', models.TextField(blank=True, default='Any sickness, injuries, pregnancies, castration or other procedures should be entered here.')),
                ('vaccination_record', models.TextField(blank=True, default='The name of the vaccines alongside of the date they were administered should be entered here')),
                ('treatment_record', models.TextField(blank=True, default='Any medication or treatment, with names, dosages and frequency should be entered here')),
                ('special_needs', models.TextField(blank=True)),
                ('behavioral_notes', models.TextField(blank=True)),
                ('other_notes', models.TextField(blank=True)),
                ('charter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='housed_dogs', to='records.charter')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dogs', to='records.contact')),
            ],
        ),
        migrations.CreateModel(
            name='DogDocumentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('document', models.FileField(upload_to='documents/')),
                ('title', models.CharField(max_length=200)),
                ('document_type', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='records.dog')),
            ],
            options={
                'ordering': ['-uploaded'],
            },
        ),
        migrations.CreateModel(
            name='DogPhotoRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=64)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('is_profile_photo', models.BooleanField(default=False)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='records.dog')),
            ],
            options={
                'ordering': ['-is_profile_photo', 'uploaded'],
            },
        ),
        migrations.CreateModel(
            name='DogWeightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('weight_kg', models.FloatField()),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_history', to='records.dog')),
            ],
            options={
                'ordering': ['-record_date'],
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='entity_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='records.entityinfo'),
        ),
        migrations.AddField(
            model_name='charter',
            name='entity_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='records.entityinfo'),
        ),
    ]
