# Generated by Django 5.2.6 on 2025-09-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.CharField(choices=[('D', 'Street Dog'), ('MIXED', 'Mixed Breed'), ('GOLDEN', 'Golden Retriever'), ('GERMAN', 'German Shepherd'), ('LAB', 'Labrador Retriever'), ('BEAGLE', 'Beagle'), ('BULL', 'Bulldog'), ('PIT', 'Pit Bull'), ('HUSKY', 'Siberian Husky'), ('CHI', 'Chihuahua'), ('POM', 'Pomeranian'), ('OTHER', 'Other')], default='D', max_length=32),
        ),
        migrations.AlterField(
            model_name='dog',
            name='color',
            field=models.CharField(choices=[('B', 'Black'), ('W', 'White'), ('G', 'Gray'), ('BR', 'Brown'), ('T', 'Tan'), ('C', 'Cream'), ('GOLD', 'Golden'), ('R', 'Red'), ('BL', 'Blue'), ('MC', 'Multi-Color'), ('SP', 'Spotted'), ('ST', 'Striped')], max_length=32),
        ),
    ]
