# Generated by Django 5.2.6 on 2025-09-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_contact_notes_alter_dog_breed_alter_dog_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='default_photo',
            field=models.ImageField(blank=True, help_text='Default photo for this dog', null=True, upload_to='photos/'),
        ),
    ]
