# Generated by Django 5.2.6 on 2025-09-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_dog_default_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='eligible_for_adoption',
        ),
        migrations.AlterField(
            model_name='adoptee',
            name='adoption_status',
            field=models.CharField(choices=[('F', 'Fit'), ('U', 'Unfit'), ('T', 'Trial'), ('A', 'Adopted'), ('NA', 'Not Available')], default='F', max_length=32),
        ),
        migrations.AlterField(
            model_name='dog',
            name='adoption_status',
            field=models.CharField(choices=[('F', 'Fit'), ('U', 'Unfit'), ('T', 'Trial'), ('A', 'Adopted'), ('NA', 'Not Available')], default='NA', max_length=32),
        ),
    ]
