# Generated by Django 5.2.6 on 2025-09-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_remove_dog_eligible_for_adoption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptee',
            name='adoption_status',
            field=models.CharField(choices=[('F', 'Fit'), ('U', 'Unfit'), ('T', 'Trial'), ('A', 'Adopted'), ('NA', 'Unspecified')], default='F', max_length=32),
        ),
        migrations.AlterField(
            model_name='dog',
            name='adoption_status',
            field=models.CharField(choices=[('F', 'Fit'), ('U', 'Unfit'), ('T', 'Trial'), ('A', 'Adopted'), ('NA', 'Unspecified')], default='NA', max_length=32),
        ),
        migrations.AlterField(
            model_name='dog',
            name='health_status',
            field=models.CharField(choices=[('H', 'Healthy'), ('S', 'Sick'), ('P', 'Passed Away'), ('U', 'Unspecified')], default='U', max_length=32),
        ),
    ]
